name: 🚀 Deploy Node.js Server on Push

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy Node.js Server
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Set up Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Sync files to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.GIT_CPANEL_SERVER }}
          username: ${{ secrets.GIT_CPANEL_USERNAME }}
          password: ${{ secrets.GIT_CPANEL_PASSWORD }}
          protocol: ftps  # Use 'ftps' for FTP Secure or 'sftp' based on your cPanel configuration
          local-dir: ../

      # Remove SSH-related steps

      # Optionally, if you need to restart the server or run additional commands,
      # you can consider adding API calls or FTP-based commands that your cPanel supports.
